from pathlib import Path


def insert_once(path, marker, block, guard):
    p = Path(path)
    text = p.read_text(encoding='utf-8')
    if guard in text:
        print(f'{path}: already enriched')
        return False
    if marker not in text:
        raise SystemExit(f'{path}: insertion marker not found')
    text = text.replace(marker, block + '\n' + marker, 1)
    p.write_text(text, encoding='utf-8')
    print(f'{path}: enriched')
    return True

research_block = '''<section id="theme-routes" class="section"><div class="shell"><div class="section-head"><div><div class="kicker">Follow a research theme</div><h2>Move across results, visions and notes.</h2></div><p>Each route connects the research architecture to published evidence, future questions and explanatory notes on the same mathematical theme.</p></div><div class="quick"><a href="../publications/#journals">Anisotropic FEM results<span>Peer-reviewed papers on geometry, interpolation, CR–RT, Morley, Nitsche and DG</span></a><a href="../blog/#geometry">Geometry notes<span>Mesh regularity, semi-regularity, graded meshes and layer-adapted meshes</span></a><a href="../fem/#vision20">CR–RT / DMP / maximum norm<span>Vision 20: pointwise structure beyond interpolation estimates</span></a><a href="../fem/#vision21">Nédélec / de Rham / Maxwell<span>Vision 21: the three-dimensional complex and certified Maxwell programme</span></a><a href="../publications/#preprints">Memory and delay preprints<span>Public manuscripts on positive-type memory, graph spaces and kernel stability</span></a><a href="../blog/#memory">Unresolved-dynamics notes<span>From hidden-state elimination to stable reduction and structure-preserving discretisation</span></a><a href="../fem/#vision18">Stable reduction<span>Vision 18: unresolved dynamics as a mathematical reduction problem</span></a><a href="../geo/">Geometric conditions in FEM<span>Historical route from classical angle conditions to computable geometry</span></a></div></div></section>'''

publications_block = '''<section id="theme-routes" class="section"><div class="shell"><div class="section-head"><div><div class="kicker">Follow the research themes</div><h2>From a paper to the surrounding programme.</h2></div><p>The publication list records formal results. These links connect each major line to its research architecture, explanatory notes and next questions.</p></div><div class="quick"><a href="../research/#fem-summary">Geometry &amp; anisotropic FEM<span>How the published interpolation, CR–RT, Morley, Nitsche and DG results fit together</span></a><a href="../blog/#geometry">Geometry Blog series<span>Explanations of mesh conditions, graded meshes, Shishkin meshes and anisotropy</span></a><a href="../fem/#vision20">DMP &amp; maximum norm<span>Next questions on monotonicity, pointwise bounds and connectivity</span></a><a href="../fem/#vision21">3D de Rham &amp; Maxwell<span>Extension from RT foundations to Nédélec, Hodge and Maxwell analysis</span></a><a href="../research/#stable-reduction">Memory &amp; unresolved dynamics<span>The operator-theoretic programme behind the memory and delay preprints</span></a><a href="../blog/#memory">Memory Blog series<span>Derivations, minimal models, kernel stability and full discretisation</span></a><a href="../blog/#curved">Exact-curved FEM series<span>Background and implementation route around the exact-curved preprint</span></a><a href="../fem/#vision17">Certification &amp; AI4Math<span>How verified output, formal reasoning and reusable certificates develop next</span></a></div></div></section>'''

visions_block = '''<section id="evidence-routes" class="section"><div class="shell"><div class="section-head"><div><div class="kicker">From vision to evidence</div><h2>See what is already proved and what is still open.</h2></div><p>Research Visions deliberately mixes established foundations with future questions. These routes separate the existing results from the next mathematical steps.</p></div><div class="quick"><a href="../research/#fem-summary">Established FEM foundations<span>Current mathematical architecture and completed strands</span></a><a href="../publications/#journals">Peer-reviewed evidence<span>Published journal papers supporting the geometry and FEM programme</span></a><a href="../blog/#geometry">Geometry notes<span>Detailed explanations behind Visions 20 and 21</span></a><a href="../publications/#preprints">Current public manuscripts<span>Memory, exact-curved geometry, certification and spherical-mesh preprints</span></a><a href="../research/#stable-reduction">Stable-reduction programme<span>Research architecture behind Vision 18</span></a><a href="../blog/#memory">Memory &amp; reduction notes<span>Calculations and model questions behind Visions 11 and 18</span></a><a href="../blog/#curved">Exact-curved notes<span>Development path behind Vision 10</span></a><a href="../blog/#certified">Certification notes<span>Public notes supporting Vision 17</span></a></div></div></section>'''

blog_block = '''<section id="research-routes" class="section"><div class="shell"><div class="section-head"><div><div class="kicker">From notes to formal research</div><h2>Use each series as a route into the research programme.</h2></div><p>The Blog explains calculations and bottlenecks; the Research, Publications and Visions pages show which parts are established, public manuscripts or future questions.</p></div><div class="quick"><a href="../research/#fem-summary">FEM research architecture<span>Where the geometry, CR–RT, Nitsche, DG and certification strands fit</span></a><a href="../publications/#journals">Peer-reviewed publications<span>Formal results behind the anisotropic FEM and nonconforming-method notes</span></a><a href="../fem/#vision20">Vision 20<span>CR–RT, discrete maximum principles and maximum-norm analysis</span></a><a href="../fem/#vision21">Vision 21<span>3D Nédélec, de Rham, Hodge and Maxwell</span></a><a href="../research/#stable-reduction">Stable reduction research<span>Operator-theoretic architecture behind the memory series</span></a><a href="../publications/#preprints">Current preprints<span>Public manuscripts on memory, certification, spherical geometry and exact-curved FEM</span></a><a href="../fem/#vision18">Vision 18<span>Stable reduction theory for unresolved dynamics</span></a><a href="../fem/#vision10">Vision 10<span>Exact-curved CR–RT, shape differentiation, ALE and FSI</span></a></div></div></section>'''

changed = []
if insert_once('research/index.html', '<section class="section"><div class="shell"><div class="section-head"><div><div class="kicker">Research memo</div>', research_block, 'id="theme-routes"'):
    changed.append('research/index.html')
if insert_once('publications/index.html', '<section id="pipeline" class="section">', publications_block, 'id="theme-routes"'):
    changed.append('publications/index.html')
if insert_once('fem/index.html', '<section id="visions" class="section">', visions_block, 'id="evidence-routes"'):
    changed.append('fem/index.html')
if insert_once('blog/index.html', '<section id="core" class="section">', blog_block, 'id="research-routes"'):
    changed.append('blog/index.html')

print('Changed:', ', '.join(changed) if changed else 'none')
